spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BacThinhDB
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  # Cấu hình cho các tác vụ không đồng bộ (Async)
  task:
    execution:
      pool:
        core-size: 2
        max-size: 5
        queue-capacity: 100

logging:
  level:
    com.bacthinh.BacThinh.service: DEBUG
    com.bacthinh.BacThinh.config.audit: DEBUG
    org.springframework.data.jpa: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
open:
  api:
    title: Bac Thinh API docs
    version: v1.0.0
    description: Mo ta API service
    serverUrl: http://localhost:8080
    serverName: Server test

openapi:
  service:
    api-docs: /v3/api-docs
    group-name: api-service

app:
  jwt:
    secret-key: "rUOugZS6xjj75a4e2xksfkBi1rv0h9Oo22wASIbY+i1Zf2nCPbwgjhPw2m+r1Zj4" #your-256-bit-secret-key-change-this-in-production
    access-token-expiration: 300000 # 2 minutes
    refresh-token-expiration: 2592000000 # 30 days
    issuer: "Bac Thinh"